server:
  port: 8080
#spring:
#  redis:
#    port: 6379
#    host: localhost
#  redisson:
#    port: 6379
#    host: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phone_bill_bank
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
